/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AISummary: typeof import('./src/components/AISummary.vue')['default']
    ApexChartBase: typeof import('./src/components/graphs/ApexChartBase.vue')['default']
    BiologicalRiskChart: typeof import('./src/components/graphs/BiologicalRiskChart.vue')['default']
    KPI: typeof import('./src/components/KPI.vue')['default']
    LeafletMap: typeof import('./src/components/LeafletMap.vue')['default']
    LoadingOverlay: typeof import('./src/components/LoadingOverlay.vue')['default']
    MonthlyTrendChart: typeof import('./src/components/graphs/MonthlyTrendChart.vue')['default']
    MPDonutChart: typeof import('./src/components/graphs/MPDonutChart.vue')['default']
    MPPracticeBar: typeof import('./src/components/graphs/MPPracticeBar.vue')['default']
    MPSizeRangeAll: typeof import('./src/components/graphs/MPSizeRangeAll.vue')['default']
    MPSizeRangeChart: typeof import('./src/components/graphs/MPSizeRangeChart.vue')['default']
    PreviewCard: typeof import('./src/components/PreviewCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SampledFarms: typeof import('./src/components/SampledFarms.vue')['default']
    SiteDrilldownChart: typeof import('./src/components/graphs/SiteDrilldownChart.vue')['default']
    SourceDegradationIndex: typeof import('./src/components/graphs/SourceDegradationIndex.vue')['default']
    SourceIdentificationHeatmap: typeof import('./src/components/graphs/SourceIdentificationHeatmap.vue')['default']
  }
}
